### PR TITLE
KSU-Next: Add Mandarin translation for README

### PR DESCRIPTION
**Pull request by pys36**

### CODE REVIEW

**Comment by pys36** [comment]
@rifsxd

**Comment by rifsxd** [comment]
> @rifsxd (btw how can I contact u)

https://t.me/ksunext_requests

**Comment by rifsxd** [comment]
> @rifsxd (btw how can I contact u)

And could you make some changes?
Put all the Readme in /docs directory?

**Comment by pys36** [comment]
sure

**Pull request merged**
