### PR TITLE
Fix Build

### PR DESCRIPTION
**Pull request by CanerKaraca23**
Try clean build with llvm 18, remove all caches on GitHub actions, if it's successful, ignore this PR.

### CODE REVIEW

**Comment by rifsxd** [comment]
it caused too many conflicts, now fully reverted.
You can PR the turkish README

**Comment by rifsxd** [comment]
and next time you PR please reside to doing single commit PR instead of dumping all in 1 PR

**Comment by CanerKaraca23** [comment]
> it caused too many conflicts, now fully reverted. You can PR the turkish README

Not gonna merge this?

**Comment by rifsxd** [comment]
> > it caused too many conflicts, now fully reverted. You can PR the turkish README
> 
> Not gonna merge this?

Just look at the mess, so much in 1 commit please reside to doing single based commits in 1 PR

Screenshot_20241225-164742~2

**Comment by CanerKaraca23** [comment]
> > > it caused too many conflicts, now fully reverted. You can PR the turkish README
> > 
> > 
> > Not gonna merge this?
> 
> Just look at the mess, so much commit in 1 PR please reside to doing single based commits in 1 PR
> 
> Screenshot_20241225-164742~2

Sure, i just opened this PR to revert llvm 18. It was gonna fix the all issues.

**Pull request closed without merging**
