### PR TITLE
Updates and Improvements

### PR DESCRIPTION
**Pull request by CanerKaraca23**
- Updated and removed some unnecessary workflows
- Updated Cargo dependencies (fixes a security issue)
- Updated Gradle
- Updated NDK
- Removed unnecessary build tools version
- Removed unnecessary npm on Dependabot
- Added Turkish README

### CODE REVIEW

**Comment by rifsxd** [comment]
Is everything tested?

**Comment by rifsxd** [comment]
does bumping the kernel patches affect being not compatible with older security level devices? As long as it doesn't beak the kernel side of the workflow and compatibility then it can be merged.

**Comment by Fsah** [comment]
Türkçe BeniOku için teşekkürler Caner Bey!

**Comment by CanerKaraca23** [comment]
> Is everything tested?

Seems fine.

> does bumping the kernel patches affect being not compatible with older security level devices? As long as it doesn't beak the kernel side of the workflow and compatibility then it can be merged.

I already did before. https://github.com/rifsxd/KernelSU-Next/commit/9a71bdf891cd1b77566725780718c49321e3a975

**Comment by rifsxd** [comment]
What are the benefits for the Kernel Patch bumps

**Comment by CanerKaraca23** [comment]
> What are the benefits for the Kernel Patch bumps

Google's monthly security and kernel updates. Stability, improvements, fixes etc.

**Comment by rifsxd** [comment]
> > What are the benefits for the Kernel Patch bumps
> 
> Google's monthly security and kernel updates. Stability, improvements, fixes etc.

Okay I will go through this after I do a new release.

**Comment by CanerKaraca23** [comment]
Ready to merging

**Comment by rifsxd** [comment]
Rebase please.

**Comment by CanerKaraca23** [comment]
> Rebase please.

Rebased.

**Comment by rifsxd** [comment]
llvm-18 not found check the latest actions fro lkm build

**Comment by rifsxd** [comment]
Reverting since it breaks everything

**Comment by CanerKaraca23** [comment]
> llvm-18 not found check the latest actions fro lkm build

Worked fine on my test action https://github.com/CanerKaraca23/KernelSU-Next/actions/runs/12485487514

Can you clear caches on actions tab and try again? If it's not working again, i can revert it back. @rifsxd

**Pull request merged**
